### ISSUE TITLE
Can't compile specific ESP-IDF commit

### ISSUE THREAD

**Issue by dragazo** [esp-rs/esp-idf-sys#197]
I'll preface this by saying I'm not sure if this is an issue for this crate or `embuild`.

I've been using `branch:release/v4.4` for a while, but recently they seem to have had a breaking change that I need to roll back in my project. I saw that the `commit:<hash>` syntax was supported for specifying the ESP-IDF version (in `Cargo.toml`), so I decided to use that. Here is the entry I'm using:

```toml
[package.metadata.esp-idf-sys]
esp_idf_version = "commit:9c384419163bdb94e3f7211540a7ae31c6a7cf11"
```

It seems to correctly clone the repository and checks out the appropriate commit, but has the wrong version of submodules (likely recursively cloning them from master and then checking out the specified commit in the main repo, but without rolling the submodules back to the correct versions for said commit). On top of this, I get the following error:

```
  Note: switching to '9c384419163bdb94e3f7211540a7ae31c6a7cf11'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:

    git switch -c <new-branch-name>

  Or undo this operation with:

    git switch -

  Turn off this advice by setting config variable advice.detachedHead to false

  HEAD is now at 9c38441916 Merge branch 'bugfix/fix_sc_send_failure_and_exit_issue_v4.4' into 'release/v4.4'

  [notice] A new release of pip is available: 23.0.1 -> 23.1.2
  [notice] To update, run: python -m pip install --upgrade pip
  Using esp-idf v4.4.4 at '/home/devin/Desktop/netsblox-vm-esp32/.embuild/espressif/esp-idf/9c384419163bdb94e3f7211540a7ae31c6a7cf11'
  fatal: no tag exactly matches '9c384419163bdb94e3f7211540a7ae31c6a7cf11'
  Error: command 'LANGUAGE="" LC_ALL="C.UTF-8" "git" "--git-dir" "/home/devin/Desktop/netsblox-vm-esp32/.embuild/espressif/esp-idf/9c384419163bdb94e3f7211540a7ae31c6a7cf11/.git" "--work-tree" "/home/devin/Desktop/netsblox-vm-esp32/.embuild/espressif/esp-idf/9c384419163bdb94e3f7211540a7ae31c6a7cf11" "describe" "--all" "--exact-match"' exited with non-zero status code 128

  Caused by:
      fatal: no tag exactly matches '9c384419163bdb94e3f7211540a7ae31c6a7cf11'
```

Is there a way to fix both of these issues? I think a workaround would be to fork the ESP-IDF repository, add a new branch at the commit I want, and use branch selectors instead (which seem to work fine and only check out the single commit they refer to). I'll try that now, but ideally a commit reference to the official repo would also work.

**Comment by Vollbrecht** [comment]
All supported official release from ESP-IDF from v4.4.7 up to v5.2.2 should work. Using the release/v.4.4 is discouraged as you see its not stable. Using fully taged version like ESP_IDF_VERSION ="v4.4.7" should always work and you don't have to have the headache of upstream breakage. 

The last time i tested to use individual commits it worked for me. Though you have to be careful that the commit is not around a ESP_IDF version boundary. In upstream they often back port stuff or have otherwise divergent branches that could lead to potential problems described here, but i don't know how actionable it is to fix that for us since its a pretty niche use-case. I don't say its invalid use-case but i don't think its worthwhile to go to deep here.

That's why i am closing this for now. If someone still runs into this issue please feel free to add to this issue, than i will reopen it, or just create a new one. Thanks!
