### ISSUE TITLE
undefined reference to `app_main' with native build

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-idf-sys#20]
[esp-test-error-fixed.zip](https://github.com/esp-rs/esp-idf-sys/files/7382529/esp-test-error-fixed.zip). I added

```rust
#[export_name = "app_main"]
extern "C" fn dummy() {}
```
to get it working.

I have the latest `ldproxy` (ldproxy-0.2.0).

Seems like the [dummy cmake project](https://github.com/esp-rs/esp-idf-sys/tree/master/resources/cmake_project) isn't being includedin the native build?

CC: @N3xed

**Comment by ivmarkov** [comment]
Having an `app_main` symbol defined by default is a tricky topic. For one, `esp-idf-sys` (and its friends like `esp-idf-hal`, `esp-idf-svc`) might be pulled in as a dependency in CMake-first/PIO-first projects with a mixed C/Rust codebase, where the `app_main` symbol might already be defined in C, and the developer might want to leave it like that.

With that said, we *do* have the means to automatically define an `app_main` symbol, which does call a Rust `main` symbol that the user should provide [here](https://github.com/esp-rs/esp-idf-svc/blob/master/src/start.rs), however it currently lives in the `esp-idf-svc` crate, so you should pull a dependency on that.

It works as follows:
* If you are building a STD binary crate (typical case for cargo-first builds), the above code gets triggered automatically (because the `binstart` feature is part of `default`).
* If you are building a library crate (the usual scenario for CMake-first and PIO-first projects), `binstart` cannot be even used, as it works for binary crates only. Instead, there is a `libstart` feature but it is not default. It has less features compared to `binstart` but it still night be useful, but the user should opt-in.

With all of the above said... the questions are: 
* Shall we move the `start.rs` code from  `esp-idf-svc` to `esp-idf-sys`? Perhaps yes, because even though `esp-idf-sys` is supposed to model the ESP-IDF unsafe API *only*, it already does have a few small utilities, and furthermore, it models the building and linking of ESP-IDF builds too, so perhaps `start.rs` belongs here. Jut like the `panic_handler` definition is already [here](https://github.com/esp-rs/esp-idf-sys/blob/master/src/panic.rs). Btw it should also be protected by a feature flag, as the user might want to override it.
* Shall we leave the `binstart` feature enabled by default? Perhaps yes, as this gives more ergonomics to cargo-first projects that do build a binary crate, at the expense of less ergonomics for CMake-first and PIO-first projects that currently cannot use the `default` feature of `esp-idf-sys` (currently `esp-idf-svc`).
