### ISSUE TITLE
Compilation issue regarding MBEDTLS

### ISSUE THREAD

**Issue by Jezza** [esp-rs/esp-idf-sys#84]
It seems that [this commit](https://github.com/esp-rs/esp-idf-sys/commit/d3c1d9dff0a715229258dc058e5c4307e6adcbf2) broke the [template](https://github.com/esp-rs/esp-template).

I think it's supposed to be added into the [components list](https://github.com/esp-rs/esp-idf-sys/blob/master/build/common.rs#L32-L57), but I don't know enough of how it's built to be sure.

Workaround:
Commenting out the offending lines fixes it.

**Comment by ivmarkov** [comment]
Would be good to also paste here the compilation failure. Sometimes, the provided analysis by the issue reporter might be partial and/or incorrect. For one, this commit definitely did not broke the `no_std` template you are referring to.

As for the [esp-idf-template](https://github.com/esp-rs/esp-idf-template), it currently fails because the upstream Rust nightly fails to build on ESP-IDF, but hopefully [it would be fixed soon](https://github.com/rust-lang/rust/pull/94609).

Feel free to reopen with more details
